//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

namespace JualBeliClass
{
    public class Kategori
    {
        #region DATA MEMBER
        private string kodeKategori;
        private string nama;
        #endregion

        #region PROPERTIES
        public string KodeKategori
        {
            get { return kodeKategori; }
            set { kodeKategori = value; }
        }

        public string Nama
        {
            get { return nama; }
            set { nama = value; }
        }
        #endregion

        #region CONSTRUCTOR
        public Kategori()
        {
            KodeKategori = "";
            Nama = "";
        }
        public Kategori(string xkode, string xnama)
        {
            KodeKategori = xkode;
            Nama = xnama;
        }
        #endregion

       
        public static string BacaData(string xkriteria, string xnilaikriteria, List<Kategori> listHasil)
        {
            string sql = "";
            if (xkriteria == "") //kriteria kosong
            {
                sql = "SELECT * FROM kategori";
            }
            else
            {
                sql = "SELECT * FROM kategori WHERE " + xkriteria + " LIKE '%" + xnilaikriteria + "%'";
            }
            try
            {
                //method dijalankan
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                listHasil.Clear();
                while (hasilData.Read() == true) //untuk baca
                {
                    Kategori katgor = new Kategori();
                    katgor.KodeKategori = hasilData.GetValue(0).ToString(); //index 0 untuk kode
                    katgor.Nama = hasilData.GetValue(1).ToString(); //index 1 untuk nama dst.
                    listHasil.Add(katgor);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah Sql : " + sql;
            }
        }
        public static string TambahData(Kategori katgor)
        {
            string sql = "INSERT INTO kategori (KodeKategori,Nama) VALUES ('" + katgor.KodeKategori + "','" + katgor.Nama + "')";
            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string UbahData(Kategori katgor)
        {
            string sql = "UPDATE Kategori SET Nama = '" + katgor.Nama
                + "'WHERE KodeKategori = '" + katgor.KodeKategori + "'";
            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah Sql : " + sql;
            }
        }
        public static string HapusData(Kategori katgor)
        {
            string sql = "DELETE FROM kategori WHERE KodeKategori = '" + katgor.KodeKategori + "'";

            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }

    }
}
