//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Transactions;
using MySql.Data.MySqlClient;
namespace JualBeliClass
{
    public class NotaJual
    {
        private string noNota;
        private DateTime tanggal;
        private Pelanggan pelanggan;
        private Pegawai pegawai;
        private List<NotaJualDetil> listNotajualDetil;
        public string NoNota
        {
            get { return noNota; }
            set { noNota = value; }
        }

        public DateTime Tanggal
        {
            get { return tanggal; }
            set { tanggal = value; }
        }

        public Pelanggan Pelanggan
        {
            get { return pelanggan; }
            set { Pelanggan = value; }
        }

        public List<NotaJualDetil> NotaJualDetil
        {
            get { return listNotajualDetil; }
            private set { listNotajualDetil = value; }
        }

        public virtual Pegawai Pegawai
        {
            get { return pegawai; }
            set { pegawai = value; }
        }
        public NotaJual()
        {
            NoNota = "";
            Tanggal = DateTime.Now;
            listNotajualDetil = new List<NotaJualDetil>();
        }
        public NotaJual(string pNonota, DateTime pTanggal, Pelanggan pPelanggan, Pegawai pPegawai)
        {
            NoNota = pNonota;
            Tanggal = pTanggal;
            Pelanggan = pPelanggan;
            Pegawai = pPegawai;
            listNotajualDetil = new List<NotaJualDetil>();
        }
        public void TambahDetilBarang(Barang pBarang, int pHarga, int pJumlah)
        {
            NotaJualDetil njd = new NotaJualDetil(pBarang, pHarga, pJumlah);
            listNotajualDetil.Add(njd);
        }
        public static string TambahData(NotaJual pNotaJual)
        {
            using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew))
            {
                string sql1 = "INSERT INTO NotaJual(NoNota,Tanggal,KodePelanggan,KodePegawai) VALUES ('" + pNotaJual.NoNota + "','" + pNotaJual.Tanggal.ToString("yyyy-MM-dd hh:mm:ss") + "','" + pNotaJual.Pelanggan.KodePelanggan + "','" + pNotaJual.Pegawai.KodePegawai + "')";
                string hasil1 = ClassKoneksi.JalankanPerintahDML(sql1);
                if (hasil1 == "1")
                {
                    string hasilUpdate = "";
                    for (int i = 0; i < pNotaJual.listNotajualDetil.Count; i++)
                    {
                        string sql2 = "INSERT INTO notajualdetil(NoNota,Harga,Jumlah) VALUES ('" + pNotaJual.NoNota + "','" + pNotaJual.listNotajualDetil[i].Harga + "','" + pNotaJual.listNotajualDetil[i].Jumlah + "')";
                        string hasil2 = ClassKoneksi.JalankanPerintahDML(sql2);
                        if (hasil2 == "1")
                        {
                            //kurangi stok barang
                            hasilUpdate = Barang.UbahStokTerjual(pNotaJual.listNotajualDetil[i].Barang.KodeBarang, pNotaJual.listNotajualDetil[i].Jumlah);

                            if (hasilUpdate != "1")
                            {
                                break;
                            }
                        }
                        else
                        {
                            tranScope.Dispose();
                            return hasil2;
                        }
                    }
                    if (hasilUpdate != "1")
                    {
                        tranScope.Dispose();
                        return hasilUpdate;
                    }
                    else
                    {
                        tranScope.Complete();
                        return "1";
                    }
                }
                tranScope.Dispose();
                return hasil1;
            }
        }

       
    }
}
