//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

namespace JualBeliClass
{
    public class Pegawai
    {
        #region DATA MEMBER

        private int kodepegawai;
        private string nama;
        private string username;
        private string password;
        private DateTime tanggal;
        private string alamat;
        private int gaji;
        private Jabatan jabatan;
        #endregion

        #region PROPERTIES
        public int KodePegawai
        {
            get { return kodepegawai; }
            set
            {
                 kodepegawai = value; 
                
            }
        }

        public string Nama
        {
            get { return nama; }
            set
            {
                 nama = value;
            }
        }

        public string Username
        {
            get { return username; }
            set
            {
                 username = value; 
            }
        }

        public virtual string Password
        {
            get { return password; }
            set
            {
               password = value; 
            }
        }

        public DateTime TglLahir
        {
            get { return tanggal; }
            set { tanggal = value; }
        }

        public string Alamat
        {
            get { return alamat; }
            set
            {
                alamat = value;
            }
        }

        public int Gaji
        {
            get { return gaji; }
            set
            {
                 gaji = value; 
            }
        }

        public Jabatan Jabatan
        {
            get { return jabatan; }
            set { jabatan = value; }
        }
        #endregion

        #region CONSTRUCTOR
        public Pegawai()
        {
            KodePegawai = 0;
            Nama = "";
            TglLahir = DateTime.Now;
            Alamat = "";
            Gaji = 0;
            Username = "";
            Password = "";
            
        }
        public Pegawai(int xkode,string xnama, DateTime xtgl, string xalamat, int xgaji, string xuser, string xpass, Jabatan xjab)
        {
            KodePegawai = xkode;
            Nama = xnama;
            TglLahir = xtgl;
            Alamat = xalamat;
            Gaji = xgaji;
            Username = xuser;
            Password = xpass;
            Jabatan = xjab;

        }
        #endregion

        #region METHOD
        public static string TambahData(Pegawai peg)
        {
            string sql = "INSERT INTO pegawai(KodePegawai, Nama, TglLahir, Alamat, Gaji, Username, Password, IdJabatan) VALUES ('" + peg.KodePegawai + "','" + peg.Nama + "','" + peg.TglLahir.ToString("yyyy-MM-dd") + "','"
                + peg.Alamat + "','" + peg.Gaji + "','" + peg.Username + "','" + peg.Password + "','" + peg.Jabatan + "')";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }
        public static string UbahData(Pegawai peg)
        {
            string sql = "UPDATE pegawai SET Nama = '" + peg.Nama.Replace("'", "\\'") + "', TglLahir = '" 
                + peg.TglLahir + "', Alamat = '" + peg.Alamat + "', Gaji = '" + peg.Gaji 
                + "' WHERE KodePegawai = '" + peg.KodePegawai + "'";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }

        public static string HapusData(Pegawai peg)
        {
            string sql = "DELETE FROM pegawai WHERE KodePegawai = '" + peg.KodePegawai + "'";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }

        public static string BacaData(string kriteria, string nilaiKriteria, List<Pegawai> listHasilData)
        {
            string sql = "";
            if (kriteria == "")
            {
                sql = "SELECT p.KodePegawai, p.Nama, p.TglLahir, p.Alamat, p.Gaji, p.Username,p.Password, p.IdJabatan,j.Nama AS NamaJabatan " +
                    " FROM pegawai p INNER JOIN jabatan j ON p.IdJabatan = j.IdJabatan";
            }
            else
            {
                sql = "SELECT p.KodePegawai, p.Nama, p.TglLahir, p.Alamat, p.Gaji, p.Username,p.Password, p.IdJabatan,j.Nama AS NamaJabatan " +
                    " FROM pegawai p INNER JOIN jabatan j ON p.IdJabatan = j.IdJabatan" +
                    " WHERE " + kriteria + " LIKE '%" + nilaiKriteria + "%'";
            }
            try
            {
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                listHasilData.Clear();
                while (hasilData.Read() == true)
                {
                    Pegawai pg = new Pegawai();
                    pg.KodePegawai = int.Parse(hasilData.GetValue(0).ToString());
                    pg.Nama = hasilData.GetValue(1).ToString();
                    pg.TglLahir = DateTime.Parse(hasilData.GetValue(2).ToString());
                    pg.Alamat = hasilData.GetValue(3).ToString();
                    pg.Gaji = int.Parse(hasilData.GetValue(4).ToString());
                    pg.Username = hasilData.GetValue(5).ToString();
                    pg.Password = hasilData.GetValue(6).ToString();
                    Jabatan classJabatan = new Jabatan(hasilData.GetValue(7).ToString(), hasilData.GetValue(8).ToString());
                    pg.Jabatan = classJabatan;
                    listHasilData.Add(pg);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }

        public static string GenerateKode(string pIdJabatan, out string hasilKode)
        {

            string sql = "SELECT MAX(KodePegawai) FROM pegawai";
            hasilKode = "";
            try
            {
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                if (hasilData.Read() == true)
                {
                    int kodeTerbaru = int.Parse(hasilData.GetValue(0).ToString()) + 1;
                    if (kodeTerbaru < 10)
                    {
                        hasilKode = kodeTerbaru.ToString();
                    }
                    else
                    {
                        hasilKode = kodeTerbaru.ToString();
                    }
                }
                else
                {
                    hasilKode = "1";
                }
                return "1";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }

        public static string BuatUserBaru(Pegawai peg, string namaServer)
        {
            string sql = "CREATE USER '" + peg.Username + "'@'" + namaServer + "' IDENTIFIED BY '" + peg.Password + "'";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }

        public static string BeriHakAkses(Pegawai peg, string namaServer, string namaDatabase)
        {
            string sql = "GRANT ALL PRIVILEGES ON " + namaDatabase + ".* TO '" + peg.Username + "'@'" + namaServer + "'";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }
        #endregion
    }

}
