//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

namespace JualBeliClass
{
    public class Jabatan
    {
        private string idjabatan;
        private string namajabatan;
        public string IdJabatan
        {
            get { return idjabatan; }
            set
            {
                
                    idjabatan = value;
             }
        }

        public string NamaJabatan
        {
            get { return namajabatan; }
            set
            {
                
                    namajabatan = value;
                
            }
        }
        public Jabatan()
        {
            IdJabatan = "";
            NamaJabatan = "";
        }
        public Jabatan(string xid, string xnama)
        {
            IdJabatan = xid;
            NamaJabatan = xnama;
        }

        public static string TambahData(Jabatan jabatan)
        {
            string sql = "INSERT INTO jabatan (IdJabatan,Nama) VALUES ('" + jabatan.IdJabatan + "','" + jabatan.NamaJabatan + "')";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;

        }
        public static string UbahData(Jabatan jabatan)
        {
            string sql = "UPDATE jabatan SET Nama = '" + jabatan.NamaJabatan
                + "'WHERE IdJabatan = '" + jabatan.IdJabatan + "'";
            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }
        public static string HapusData(Jabatan jabatan)
        {
            string sql = "DELETE FROM jabatan WHERE IdJabatan = '" + jabatan.IdJabatan + "'";

            string hasil = ClassKoneksi.JalankanPerintahDML(sql);
            return hasil;
        }
        public static string BacaData(string xkriteria, string xnilaikriteria, List<Jabatan> listHasil)
        {
            string sql = "";
            if (xkriteria == "") //kriteria kosong
            {
                sql = "SELECT * FROM jabatan";
            }
            else
            {
                sql = "SELECT * FROM jabatan WHERE " + xkriteria + " LIKE '%" + xnilaikriteria + "%'";
            }
            try
            {
                //method dijalankan
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                listHasil.Clear();
                while (hasilData.Read() == true) //untuk baca
                {
                    Jabatan jabatan = new Jabatan();
                    jabatan.IdJabatan = hasilData.GetValue(0).ToString(); //index 0 untuk kode
                    jabatan.NamaJabatan = hasilData.GetValue(1).ToString(); //index 1 untuk nama dst.
                    listHasil.Add(jabatan);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah Sql : " + sql;
            }
        }
        public static string GenerateKode(out string hasilKode)
        {
            string sql = "SELECT MAX(IdJabatan) FROM jabatan";
            hasilKode = "";
            try
            {
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                if (hasilData.Read() == true)
                {
                    string kodeTerbaru = hasilData.GetValue(0).ToString();
                    string[] splitted = kodeTerbaru.Split('J');
                    int temp = int.Parse(splitted[1].ToString()) + 1;
                    if (temp < 10)
                    {
                        hasilKode = "J" + temp.ToString();
                    }
                    else
                    {
                        hasilKode = kodeTerbaru.ToString();
                    }
                }
                else
                {
                    hasilKode = "J1";
                }
                return "1";
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
    }
}

