//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Transactions;
using MySql.Data.MySqlClient;


namespace JualBeliClass
{
    public class NotaJual
    {
        private string noNota;
        private DateTime tanggal;
        private Pelanggan pelanggan;
        private Pegawai pegawai;
        private List<NotaJualDetil> listNotaJualDetil;
        public string NoNotaJual
        {
            get { return noNota; }
            set { noNota = value; }
        }

        public DateTime Tanggal
        {
            get { return tanggal; }
            set { tanggal = value; }
        }

        public Pelanggan Pelanggan
        {
            get { return pelanggan; }
            set { pelanggan = value; }
        }

        public List<NotaJualDetil> ListNotaJualDetil
        {
            get { return listNotaJualDetil; }
            private set { listNotaJualDetil = value; }
        }

        public Pegawai Pegawai
        {
            get { return pegawai; }
            set { pegawai = value; }
        }

        public NotaJual()
        {
            NoNotaJual = "";
            Tanggal = DateTime.Now;
            ListNotaJualDetil = new List<NotaJualDetil>();
        }

        public NotaJual(string pnota, DateTime ptanggal, Pelanggan ppelanggan, Pegawai ppegawai)
        {
            NoNotaJual = pnota;
            Tanggal = ptanggal;
            Pelanggan = ppelanggan;
            Pegawai = ppegawai;
            ListNotaJualDetil = new List<NotaJualDetil>();
        }

        public void TambahDetilBarang(Barang pbarang, int pharga, int pjumlah)
        {
            NotaJualDetil notaJual = new NotaJualDetil(pbarang, pharga, pjumlah);
            ListNotaJualDetil.Add(notaJual);
        }

        public static string TambahData(NotaJual pNotaJual)
        {
            #region RAHASIA
            //using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew))
            //{
            //    string sql1 = "INSERT INTO NotaJual (NoNota, Tanggal, KodePelanggan, KodePegawai) VALUES ('" + pNotaJual.NoNotaJual + "','" +
            //       pNotaJual.Tanggal.ToString("yyyy-MM-dd hh:mm:ss") + "','" + pNotaJual.Pelanggan.KodePelanggan + "','" + pNotaJual.Pegawai.KodePegawai + "')";

            //    try
            //    {

            //        ClassKoneksi.JalankanPerintahDML(sql1);

            //        for (int i = 0; i < pNotaJual.ListNotaJualDetil.Count; i++)
            //        {
            //            string sql2 = "INSERT INTO NotaJualDetil(NoNota, KodeBarang, Harga, Jumlah) VALUES ('" + pNotaJual.NoNotaJual + "','" +
            //            pNotaJual.ListNotaJualDetil[i].Barang.KodeBarang + "','" + pNotaJual.ListNotaJualDetil[i].Harga + "','" + pNotaJual.ListNotaJualDetil[i].Jumlah + "')";

            //            ClassKoneksi.JalankanPerintahDML(sql2);

            //            string hasilUpdate = Barang.UbahStokTerjual(pNotaJual.ListNotaJualDetil[i].Barang.KodeBarang, pNotaJual.ListNotaJualDetil[i].Jumlah);
            //        }


            //        return "1";
            //    }
            //    catch (Exception e)
            //    {
            //        return e.Message;
            //    }

            //}
            #endregion

            using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew))
            {

                string sql1 = "INSERT INTO NotaJual(NoNota ,Tanggal, KodePelanggan, KodePegawai) VALUES ('" + pNotaJual.NoNotaJual + "','" + pNotaJual.Tanggal.ToString("yyyy-MM-dd hh:mm:ss") + "','" + pNotaJual.Pelanggan.KodePelanggan + "','" + pNotaJual.Pegawai.KodePegawai + "')";
                string hasil1 = ClassKoneksi.JalankanPerintahDML(sql1);
                if (hasil1 == "1")
                {
                    string hasilUpdate = "";
                    for (int i = 0; i < pNotaJual.ListNotaJualDetil.Count; i++)
                    {
                        string sql2 = "INSERT INTO notajualdetil(NoNota,Harga,Jumlah) VALUES ('" + pNotaJual.NoNotaJual + "','" + pNotaJual.ListNotaJualDetil[i].Harga + "','" + pNotaJual.ListNotaJualDetil[i].Jumlah + "')";
                        string hasil2 = ClassKoneksi.JalankanPerintahDML(sql2);
                        if (hasil2 == "1")
                        {
                            //kurangi stok barang
                            hasilUpdate = Barang.UbahStokTerjual(pNotaJual.ListNotaJualDetil[i].Barang.KodeBarang, pNotaJual.listNotaJualDetil[i].Jumlah);

                            if (hasilUpdate != "1")
                            {
                                break;
                            }
                        }
                        else
                        {
                            ////tranScope.Dispose();
                            return hasil2;
                        }  
                    }
                    if (hasilUpdate != "1")
                    {
                        tranScope.Dispose();
                        return hasilUpdate;
                    }
                    else
                    {
                        tranScope.Complete();
                        return "1";
                    }
                }
                tranScope.Dispose();
                return hasil1;
            }
            
            
        }

        public static string GenerateHasilNoNota(out string phasilNoNota)
        {
            string sql = "SELECT SUBSTRING(NoNota,9,3) AS noUrutTransaksi " + " FROM NotaJual " + " WHERE Date(tanggal) = Date(CURRENT_DATE()) " + " ORDER BY NoNota DESC LIMIT 1";

            phasilNoNota = "";
            try
            {
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);

                string noUrutTerbaru = "";
                if (hasilData.Read() == true)//ada ata
                {
                    int noBaru = int.Parse(hasilData.GetValue(0).ToString()) + 1;
                    noUrutTerbaru = noBaru.ToString().PadLeft(3, '0');
                }
                else//no data
                {
                    noUrutTerbaru = "001";
                }

                string tahun = DateTime.Now.Year.ToString();
                string bulan = DateTime.Now.Month.ToString().PadLeft(2, '0');
                string hari = DateTime.Now.Day.ToString().PadLeft(2, '0');

                phasilNoNota = tahun + bulan + hari + noUrutTerbaru.ToString();
                return "1";
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
        }


    }

    

}
