//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JualBeliClass
{
    public class NotaBeliDetil
    {
        public virtual long Harga
        {
            get;
            set;
        }

        public virtual int Jumlah
        {
            get;
            set;
        }

        public virtual Barang Barang
        {
            get;
            set;
        }

    }
}

