//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JualBeliClass
{
    public class NotaBeli
    {
        public virtual string NoNotaBeli
        {
            get;
            set;
        }

        public virtual DateTime Tanggal
        {
            get;
            set;
        }

        public virtual IEnumerable<NotaBeliDetil> NotaBeliDetil
        {
            get;
            set;
        }

        public virtual Pegawai Pegawai
        {
            get;
            set;
        }

        public virtual Supplier Supplier
        {
            get;
            set;
        }

    }
}

