//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

namespace JualBeliClass
{
    public class Pelanggan
    {
        #region DATA MEMBER
        private int kodepelanggan;
        private string nama;
        private string alamat;
        private string telepon;
       
        #endregion

        #region PROPERTIES
        public int KodePelanggan
        {
            get { return kodepelanggan; }
            set { kodepelanggan = value; }
        }

        public string Nama
        {
            get { return nama; }
            set { nama = value; }
        }

        public string Alamat
        {
            get { return alamat; }
            set { alamat = value; }
        }

        public string Telepon
        {
            get { return telepon; }
            set { telepon = value; }
        }
        #endregion

        #region CONSTRUCTOR
        public Pelanggan()
        {
            KodePelanggan = 0;
            Nama = "";
            Alamat = "";
            Telepon = "";
        }
        public Pelanggan(int xkode, string xnama, string xalamat, string xtelepon)
        {
            KodePelanggan = xkode;
            Nama = xnama;
            Alamat = xalamat;
            Telepon = xtelepon;
        }
        #endregion

        #region METHOD
        
        public static string TambahData(Pelanggan pelangn)
        {
            string sql = "INSERT INTO pelanggan (KodePelanggan,Nama,Alamat,Telepon) VALUES ('" + pelangn.KodePelanggan + "','" + pelangn.Nama +
                "','" + pelangn.Alamat + "','" + pelangn.Telepon + "')";
            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
             
            
        }
        public static string UbahData(Pelanggan pelangn)
        {
            string sql = "UPDATE pelanggan SET Nama = '" + pelangn.Nama + "', KodePelanggan = '" + pelangn.KodePelanggan + "', Alamat = '"
               + pelangn.Alamat + "', Telepon = '" + pelangn.Telepon + "' WHERE KodePelanggan = '" + pelangn.KodePelanggan + "'";
            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah Sql : " + sql;
            }
        }

        public static string HapusData(Pelanggan pelangn)
        {
            string sql = "DELETE FROM pelanggan WHERE KodePelanggan = '" + pelangn.KodePelanggan + "'";

            try
            {
                ClassKoneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }


        public static string BacaData(string kriteria, string nilaikriteria, List<Pelanggan> listHasil)
        {
            string sql = "";
            if (kriteria == "") //kriteria kosong
            {
                sql = "SELECT * FROM pelanggan";
            }
            else
            {
                sql = "SELECT * FROM pelanggan WHERE " + kriteria + " LIKE '%" + nilaikriteria + "%'";
            }
            try
            {
                //method dijalankan
                MySqlDataReader hasilData = ClassKoneksi.JalankanPerintahQuery(sql);
                listHasil.Clear();
                while (hasilData.Read() ==  true) //untuk baca
                {
                    Pelanggan pelagn = new Pelanggan();
                    pelagn.KodePelanggan = int.Parse(hasilData.GetValue(0).ToString()); //index 0 untuk kode
                    pelagn.Nama = hasilData.GetValue(1).ToString(); //index 1 untuk nama dst.
                    pelagn.Alamat = hasilData.GetValue(2).ToString();
                    pelagn.Telepon = hasilData.GetValue(3).ToString();
                    listHasil.Add(pelagn);
                }
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }

        public static string generatecode(out string hasilkode)
        {
            string sql = "SELECT MAX(KodePelanggan) FROM pelanggan";
            hasilkode = "";
            try
            {
                MySqlDataReader hasildata = ClassKoneksi.JalankanPerintahQuery(sql);
                if (hasildata.Read() == true)
                {
                    int kodeterbaru = int.Parse(hasildata.GetValue(0).ToString()) + 1;
                    if (kodeterbaru < 10)
                    {
                        hasilkode = "0" + kodeterbaru;
                    }
                    else
                    {
                        hasilkode = kodeterbaru.ToString();
                    }

                }
                else
                {
                    hasilkode = "01";
                }
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        #endregion

    }


}