//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JualBeliClass
{
    public class Supplier
    {
        public virtual int KodeSupplier
        {
            get;
            set;
        }

        public virtual string Nama
        {
            get;
            set;
        }

        public virtual string Alamat
        {
            get;
            set;
        }

    }


}