//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JualBeliClass
{
    public class Barang
    {
        public virtual string KodeBarang
        {
            get;
            set;
        }

        public virtual string Nama
        {
            get;
            set;
        }

        public virtual long HargaJual
        {
            get;
            set;
        }

        public virtual int Stok
        {
            get;
            set;
        }

        public virtual string Barcode
        {
            get;
            set;
        }

        public virtual Kategori Kategori
	    {
		    get;
		    set;
        }
}
}
    


