//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MySql.Data.MySqlClient;

namespace JualBeliClass
{
    public class Kategori
    {
        #region DATA MEMBER
        private string kodeKategori;
        private string nama;
        #endregion

        #region PROPERTIES
        public string KodeKategori
        {
            get;
            set;
        }

        public string Nama
        {
            get;
            set;
        }
        #endregion

        #region CONSTRUCTOR
        public Kategori()
        {
            KodeKategori = "";
            Nama = "";
        }
        public Kategori(string xkode, string xnama)
        {
            KodeKategori = xkode;
            Nama = xnama;
        }
        #endregion

        private static void JalankanPerintahDML(string pSql)
        {
            ClassKoneksi koneksi = new ClassKoneksi();
            koneksi.Connect();

            //Buat mysql command
            MySqlCommand konek = new MySqlCommand(pSql, koneksi.KoneksiDB);
            //Gunakan ExecutionQuery untuk insert,delete,update
            konek.ExecuteNonQuery();
        }
        public static string TambahData(Kategori katgor)
        {
            string sql = "Insert Into Kategori ('KodeKategori','Nama') Values ('" + katgor.KodeKategori + "','" + katgor.Nama + "')";//kat.nama.replace("'","\\'")
            try
            {
                JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        public static string UbahData(Kategori katgor)
        {
            string sql = "Update Kategori Set nama = '" + katgor.Nama.Replace("'", "\\'")
                + "'Where KodeKategori = '" + katgor.KodeKategori + "'";
            try
            {
                JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah Sql : " + sql;
            }
        }
        public static string HapusData(Kategori katgor)
        {
            string sql = "Delete From kategori Where KodeKategori = '" + katgor.KodeKategori + "'";

            try
            {
                JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException ex)
            {
                return ex.Message + ". Perintah sql : " + sql;
            }
        }
        private static MySqlDataReader JalankanPerintahQuery (string pSql)
        {
            ClassKoneksi k = new ClassKoneksi();
            MySqlCommand c = new MySqlCommand(pSql, k.KoneksiDB);
            MySqlDataReader hasilData = c.ExecuteReader();

            return hasilData;
        }
        public static string BacaData(List<Kategori> listHasil, string pKriteria, string pNilaiKriteria)
        {
            string sql = "";
           if (pKriteria == "")
           {
               sql = "SELECT * FROM kategori";
           }
           else
           {
               sql = "SELECT * FROM kategori WHERE " + pKriteria + " LIKE '%" + pNilaiKriteria + "%'";
           }
           try
           {
               
               MySqlDataReader hasilData = JalankanPerintahQuery(sql);
               while (hasilData.Read() == true)
               {
                   Kategori kt = new Kategori();
                   kt.KodeKategori = hasilData.GetValue(0).ToString();
                   kt.Nama = hasilData.GetValue(1).ToString();
                   listHasil.Add(kt);
               }
               return "1";
           }
            
            catch (MySqlException ex)
           {
                return ex.Message + ". perintah sql : " + sql;
           }
        }

    }
}
