//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JualBeliClass
{
    public class Pegawai
    {
        public virtual int KodePegawai
        {
            get;
            set;
        }

        public virtual string Nama
        {
            get;
            set;
        }

        public virtual string Username
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual DateTime TglLahir
        {
            get;
            set;
        }

        public virtual string Alamat
        {
            get;
            set;
        }

        public virtual int Gaji
        {
            get;
            set;
        }

        public virtual Jabatan Jabatan
        {
            get;
            set;
        }

    }

}
